services:
  # 1. Le Serveur de Base de Données
  db:
    image: postgres:15
    container_name: secmar_postgres
    restart: always
    environment:
      POSTGRES_USER: admin # Ton login
      POSTGRES_PASSWORD: admin # Ton mot de passe
      POSTGRES_DB: maritime # Le nom de la base
    ports:
      - "5432:5432" # Ouvre le port sur ton PC
    volumes:
      - pg_data:/var/lib/postgresql/data # Pour ne pas perdre les données si tu éteins Docker

  # 2. L'interface visuelle (Optionnel mais pratique)
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  pg_data:
